devices:
  tofino1:
    name: "tofino1"
    type: "tofino"

    ports:
      1/-:
          name: "1/-"
          phys: 1
          internal: 128
          pipe: 3
      2/-:
          name: "2/-"
          phys: 2
          internal: 136
          pipe: 3
      3/-:
          name: "3/-"
          phys: 3
          internal: 144
          pipe: 3
      4/-:
          name: "4/-"
          phys: 4
          internal: 152
          pipe: 3
      5/-:
          name: "5/-"
          phys: 5
          internal: 160
          pipe: 3
      6/-:
          name: "6/-"
          phys: 6
          internal: 168
          pipe: 3
      7/-:
          name: "7/-"
          phys: 7
          internal: 176
          pipe: 3
      8/-:
          name: "8/-"
          phys: 8
          internal: 184
          pipe: 3
      9/-:
          name: "9/-"
          phys: 9
          internal: 60
          pipe: 1
      10/-:
          name: "10/-"
          phys: 10
          internal: 52
          pipe: 1
      11/-:
          name: "11/-"
          phys: 11
          internal: 44
          pipe: 1

      12/-:
          name: "12/-"
          phys: 12
          internal: 36
          pipe: 1
      13/-:
          name: "13/-"
          phys: 13
          internal: 28
          pipe: 1
      14/-:
          name: "14/-"
          phys: 14
          internal: 20
          pipe: 1
      15/-:
          name: "15/-"
          phys: 15
          internal: 12
          pipe: 1
      16/-:
          name: "16/-"
          phys: 16
          internal: 4
          pipe: 1
      17/-:
          name: "17/-"
          phys: 17
          internal: 0
          pipe: 1
      18/-:
          name: "18/-"
          phys: 18
          internal: 8
          pipe: 1
      19/-:
          name: "19/-"
          phys: 19
          internal: 16
          pipe: 1
      20/-:
          name: "20/-"
          phys: 20
          internal: 24
          pipe: 1
      21/-:
          name: "21/-"
          phys: 21
          internal: 32
          pipe: 1
      22/-:
          name: "22/-"
          phys: 22
          internal: 40
          pipe: 1
      23/-:
          name: "23/-"
          phys: 23
          internal: 48
          pipe: 1
      24/-:
          name: "24/-"
          phys: 24
          internal: 56
          pipe: 1
      25/-:
          name: "25/-"
          phys: 25
          internal: 188
          pipe: 3
      26/-:
          name: "26/-"
          phys: 26
          internal: 180
          pipe: 3
      27/-:
          name: "27/-"
          phys: 27
          internal: 172
          pipe: 3
      28/-:
          name: "28/-"
          phys: 28
          internal: 164
          pipe: 3
      29/-:
          name: "29/-"
          phys: 29
          internal: 148
          pipe: 3
      30/-:
          name: "30/-"
          phys: 30
          internal: 156
          pipe: 3
      31/-:
          name: "31/-"
          phys: 31
          internal: 132
          pipe: 3
      32/-:
          name: "32/-"
          phys: 32
          internal: 140
          pipe: 3


      1/0:
          name: "1/0"
          phys: 1
          internal: 128
          pipe: 3
      1/1:
          name: "1/1"
          phys: 1
          internal: 129
          pipe: 3
      1/2:
          name: "1/2"
          phys: 1
          internal: 130
          pipe: 3
      1/3:
          name: "1/3"
          phys: 1
          internal: 131
          pipe: 3
      2/0:
          name: "2/0"
          phys: 2
          internal: 136
          pipe: 3
      2/1:
          name: "2/1"
          phys: 2
          internal: 137
          pipe: 3
      2/2:
          name: "2/2"
          phys: 2
          internal: 138
          pipe: 3
      2/3:
          name: "2/3"
          phys: 2
          internal: 139
          pipe: 3
      3/0:
          name: "3/0"
          phys: 3
          internal: 144
          pipe: 3
      3/1:
          name: "3/1"
          phys: 3
          internal: 145
          pipe: 3
      3/2:
          name: "3/2"
          phys: 3
          internal: 146
          pipe: 3
      3/3:
          name: "3/3"
          phys: 3
          internal: 147
          pipe: 3
      4/0:
          name: "4/0"
          phys: 4
          internal: 152
          pipe: 3
      4/1:
          name: "4/1"
          phys: 4
          internal: 153
          pipe: 3
      4/2:
          name: "4/2"
          phys: 4
          internal: 154
          pipe: 3
      4/3:
          name: "4/3"
          phys: 4
          internal: 155
          pipe: 3
      5/0:
          name: "5/0"
          phys: 5
          internal: 160
          pipe: 3
      5/1:
          name: "5/1"
          phys: 5
          internal: 161
          pipe: 3
      5/2:
          name: "5/2"
          phys: 5
          internal: 162
          pipe: 3
      5/3:
          name: "5/3"
          phys: 5
          internal: 163
          pipe: 3
      6/0:
          name: "6/0"
          phys: 6
          internal: 168
          pipe: 3
      6/1:
          name: "6/1"
          phys: 6
          internal: 169
          pipe: 3
      6/2:
          name: "6/2"
          phys: 6
          internal: 170
          pipe: 3
      6/3:
          name: "6/3"
          phys: 6
          internal: 171
          pipe: 3
      7/0:
          name: "7/0"
          phys: 7
          internal: 176
          pipe: 3
      7/1:
          name: "7/1"
          phys: 7
          internal: 177
          pipe: 3
      7/2:
          name: "7/2"
          phys: 7
          internal: 178
          pipe: 3
      7/3:
          name: "7/3"
          phys: 7
          internal: 179
          pipe: 3
      8/0:
          name: "8/0"
          phys: 8
          internal: 184
          pipe: 3
      8/1:
          name: "8/1"
          phys: 8
          internal: 185
          pipe: 3
      8/2:
          name: "8/2"
          phys: 8
          internal: 186
          pipe: 3
      8/3:
          name: "8/3"
          phys: 8
          internal: 187
          pipe: 3
      9/0:
          name: "9/0"
          phys: 9
          internal: 60
          pipe: 1
      9/1:
          name: "9/1"
          phys: 9
          internal: 61
          pipe: 1
      9/2:
          name: "9/2"
          phys: 9
          internal: 62
          pipe: 1
      9/3:
          name: "9/3"
          phys: 9
          internal: 63
          pipe: 1
      10/0:
          name: "10/0"
          phys: 10
          internal: 52
          pipe: 1
      10/1:
          name: "10/1"
          phys: 10
          internal: 53
          pipe: 1
      10/2:
          name: "10/2"
          phys: 10
          internal: 54
          pipe: 1
      10/3:
          name: "10/3"
          phys: 10
          internal: 55
          pipe: 1
      11/0:
          name: "11/0"
          phys: 11
          internal: 44
          pipe: 1
      11/1:
          name: "11/1"
          phys: 11
          internal: 45
          pipe: 1
      11/2:
          name: "11/2"
          phys: 11
          internal: 46
          pipe: 1
      11/3:
          name: "11/3"
          phys: 11
          internal: 47
          pipe: 1
      12/0:
          name: "12/0"
          phys: 12
          internal: 36
          pipe: 1
      12/1:
          name: "12/1"
          phys: 12
          internal: 37
          pipe: 1
      12/2:
          name: "12/2"
          phys: 12
          internal: 38
          pipe: 1
      12/3:
          name: "12/3"
          phys: 12
          internal: 39
          pipe: 1
      13/0:
          name: "13/0"
          phys: 13
          internal: 28
          pipe: 1
      13/1:
          name: "13/1"
          phys: 13
          internal: 29
          pipe: 1
      13/2:
          name: "13/2"
          phys: 13
          internal: 30
          pipe: 1
      13/3:
          name: "13/3"
          phys: 13
          internal: 31
          pipe: 1
      14/0:
          name: "14/0"
          phys: 14
          internal: 20
          pipe: 1
      14/1:
          name: "14/1"
          phys: 14
          internal: 21
          pipe: 1
      14/2:
          name: "14/2"
          phys: 14
          internal: 22
          pipe: 1
      14/3:
          name: "14/3"
          phys: 14
          internal: 23
          pipe: 1
      15/0:
          name: "15/0"
          phys: 15
          internal: 12
          pipe: 1
      15/1:
          name: "15/1"
          phys: 15
          internal: 13
          pipe: 1
      15/2:
          name: "15/2"
          phys: 15
          internal: 14
          pipe: 1
      15/3:
          name: "15/3"
          phys: 15
          internal: 15
          pipe: 1
      16/0:
          name: "16/0"
          phys: 16
          internal: 4
          pipe: 1
      16/1:
          name: "16/1"
          phys: 16
          internal: 5
          pipe: 1
      16/2:
          name: "16/2"
          phys: 16
          internal: 6
          pipe: 1
      16/3:
          name: "16/3"
          phys: 16
          internal: 7
          pipe: 1
      17/0:
          name: "17/0"
          phys: 17
          internal: 0
          pipe: 1
      17/1:
          name: "17/1"
          phys: 17
          internal: 1
          pipe: 1
      17/2:
          name: "17/2"
          phys: 17
          internal: 2
          pipe: 1
      17/3:
          name: "17/3"
          phys: 17
          internal: 3
          pipe: 1
      18/0:
          name: "18/0"
          phys: 18
          internal: 8
          pipe: 1
      18/1:
          name: "18/1"
          phys: 18
          internal: 9
          pipe: 1
      18/2:
          name: "18/2"
          phys: 18
          internal: 10
          pipe: 1
      18/3:
          name: "18/3"
          phys: 18
          internal: 11
          pipe: 1
      19/0:
          name: "19/0"
          phys: 19
          internal: 16
          pipe: 1
      19/1:
          name: "19/1"
          phys: 19
          internal: 17
          pipe: 1
      19/2:
          name: "19/2"
          phys: 19
          internal: 18
          pipe: 1
      19/3:
          name: "19/3"
          phys: 19
          internal: 19
          pipe: 1
      20/0:
          name: "20/0"
          phys: 20
          internal: 24
          pipe: 1
      20/1:
          name: "20/1"
          phys: 20
          internal: 25
          pipe: 1
      20/2:
          name: "20/2"
          phys: 20
          internal: 26
          pipe: 1
      20/3:
          name: "20/3"
          phys: 20
          internal: 27
          pipe: 1
      21/0:
          name: "21/0"
          phys: 21
          internal: 32
          pipe: 1
      21/1:
          name: "21/1"
          phys: 21
          internal: 33
          pipe: 1
      21/2:
          name: "21/2"
          phys: 21
          internal: 34
          pipe: 1
      21/3:
          name: "21/3"
          phys: 21
          internal: 35
          pipe: 1
      22/0:
          name: "22/0"
          phys: 22
          internal: 40
          pipe: 1
      22/1:
          name: "22/1"
          phys: 22
          internal: 41
          pipe: 1
      22/2:
          name: "22/2"
          phys: 22
          internal: 42
          pipe: 1
      22/3:
          name: "22/3"
          phys: 22
          internal: 43
          pipe: 1
      23/0:
          name: "23/0"
          phys: 23
          internal: 48
          pipe: 1
      23/1:
          name: "23/1"
          phys: 23
          internal: 49
          pipe: 1
      23/2:
          name: "23/2"
          phys: 23
          internal: 50
          pipe: 1
      23/3:
          name: "23/3"
          phys: 23
          internal: 51
          pipe: 1
      24/0:
          name: "24/0"
          phys: 24
          internal: 56
          pipe: 1
      24/1:
          name: "24/1"
          phys: 24
          internal: 57
          pipe: 1
      24/2:
          name: "24/2"
          phys: 24
          internal: 58
          pipe: 1
      24/3:
          name: "24/3"
          phys: 24
          internal: 59
          pipe: 1
      25/0:
          name: "25/0"
          phys: 25
          internal: 188
          pipe: 3
      25/1:
          name: "25/1"
          phys: 25
          internal: 189
          pipe: 3
      25/2:
          name: "25/2"
          phys: 25
          internal: 190
          pipe: 3
      25/3:
          name: "25/3"
          phys: 25
          internal: 191
          pipe: 3
      26/0:
          name: "26/0"
          phys: 26
          internal: 180
          pipe: 3
      26/1:
          name: "26/1"
          phys: 26
          internal: 181
          pipe: 3
      26/2:
          name: "26/2"
          phys: 26
          internal: 182
          pipe: 3
      26/3:
          name: "26/3"
          phys: 26
          internal: 183
          pipe: 3
      27/0:
          name: "27/0"
          phys: 27
          internal: 172
          pipe: 3
      27/1:
          name: "27/1"
          phys: 27
          internal: 173
          pipe: 3
      27/2:
          name: "27/2"
          phys: 27
          internal: 174
          pipe: 3
      27/3:
          name: "27/3"
          phys: 27
          internal: 175
          pipe: 3
      28/0:
          name: "28/0"
          phys: 28
          internal: 164
          pipe: 3
      28/1:
          name: "28/1"
          phys: 28
          internal: 165
          pipe: 3
      28/2:
          name: "28/2"
          phys: 28
          internal: 166
          pipe: 3
      28/3:
          name: "28/3"
          phys: 28
          internal: 167
          pipe: 3
      29/0:
          name: "29/0"
          phys: 29
          internal: 148
          pipe: 3
      29/1:
          name: "29/1"
          phys: 29
          internal: 149
          pipe: 3
      29/2:
          name: "29/2"
          phys: 29
          internal: 150
          pipe: 3
      29/3:
          name: "29/3"
          phys: 29
          internal: 151
          pipe: 3
      30/0:
          name: "30/0"
          phys: 30
          internal: 156
          pipe: 3
      30/1:
          name: "30/1"
          phys: 30
          internal: 157
          pipe: 3
      30/2:
          name: "30/2"
          phys: 30
          internal: 158
          pipe: 3
      30/3:
          name: "30/3"
          phys: 30
          internal: 159
          pipe: 3
      31/0:
          name: "31/0"
          phys: 31
          internal: 132
          pipe: 3
      31/1:
          name: "31/1"
          phys: 31
          internal: 133
          pipe: 3
      31/2:
          name: "31/2"
          phys: 31
          internal: 134
          pipe: 3
      31/3:
          name: "31/3"
          phys: 31
          internal: 135
          pipe: 3
      32/0:
          name: "32/0"
          phys: 32
          internal: 140
          pipe: 3
      32/1:
          name: "32/1"
          phys: 32
          internal: 141
          pipe: 3
      32/2:
          name: "32/2"
          phys: 32
          internal: 142
          pipe: 3
      32/3:
          name: "32/3"
          phys: 32
          internal: 143
          pipe: 3